runtime: nodejs18

instance_class: F1

handlers:
  - url: /static
    static_dir: public/static
    expiration: 30d
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
